apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: busy-job
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: busy-job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - echo hello;sleep 30;echo world
            image: busybox
            name: busy-job
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
