apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-busybox
  name: multi-busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: multi-busybox2
  - args:
    - /bin/sh
    - -c 
    - echo hello;sleep 3600
    image: busybox
    name: multi-busybox1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
