apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-backend
  name: nginx-backend
spec:
  containers:
  - image: busybox
    name: busybox
  - image: nginx
    name: nginx-backend
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: top-secret
            key: key1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
