apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: pi
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: pi
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - perl
            - -Mbignum=bpi
            - -wle
            - 'print bpi(2000)'
            image: perl
            name: pi
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
