apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: development
  name: labelex
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
